### ISSUE TITLE
MFTECmd and a live MFT

### ISSUE THREAD

**Issue by kimoppalfens** [EricZimmerman/MFTECmd#10]
Hi,

Can MFTECmd work with the MFT directly or does the MFT need to be extracted/dumped first?

**Comment by EricZimmerman** [comment]
Did you try? It's work that way forever

**Comment by kimoppalfens** [comment]
Hi Eric,

I did, but got the message that $MFT could not be found.
I probably should've included my command line I used that got me confused.
MFTECmd.exe -f $MFT --csv "c:\temp\out"

After your response I figured that I might need the complete path to $MFT>
All of the examples seem to point to using -f "C:\Temp\SomeMFT", which made me wonder.

MFTECmd.exe -f c:\$MFT --csv "c:\temp\out"
works as expected.

Thanks for the swift response, "issue" between keyboard and chair.

**Comment by EricZimmerman** [comment]
If you use PowerShell you have to enclose the path to the file in single quotes because a dollar sign in PowerShell denotes the name of a variable

If you run it in the command shell then this is not necessary

You must run the tools as an administrator regardless

You should also include the full path to the MFT so rather than just the name of the file it should be

-f 'c:\$mft' 

And so on
