### ISSUE TITLE
Feature Request: Time bracketing (e.g. EvtxECmd --sd and --ed switches)

### ISSUE THREAD

**Issue by BeanBagKing** [EricZimmerman/MFTECmd#13]
I'm looking for file events that occur between two events. It would be helpful if I could filter the results with a time braecket the same way you can with EvtxECmd. Any line containing any timestamp between those two times (Created, Last Modified, Update Timestamp for $J, etc.) are exported, the rest are discarded. 

For example:
```
MFTECmd.exe -f C:\$Extend\$UsnJrnl:$J -m C:\$mft --csv c:\Users\forensic\Desktop --sd "2023-01-22 23:24:24.0000000" --ed "2023-01-22 23:25:16.0000000"
```

**Comment by EricZimmerman** [comment]
No need really. Load the csv into timeline explorer, then use the filter on the column you want. You can pick by year month or day. 

Give it a whirl

**Comment by BeanBagKing** [comment]
Unless I'm missing something, that works on one column at a time, but not across all time columns unless you keep stacking "or" statements. I feel like it would be easier to pre-filter everything, and end up with a smaller, more manageable file.

![image](https://user-images.githubusercontent.com/5495515/213954335-a7476e76-d866-4464-a0e8-a6f5fdd4464f.png)

It's not something I need often though, so if this isn't worth implementing, or I'm misunderstanding timeline explorer, no worries.

**Comment by EricZimmerman** [comment]
Well the good news is that once you set that up tle will remember the filter so you can just reselect that previous filter from the list. 

Event logs have so many more events that a date filter on one column makes sense but needing to check up to 12 timestamps will take a lot longer.

**Comment by AndrewRathbun** [comment]
With timestomping being a thing, I would strongly recommend filtering in TLE post-parsing rather than during parsing. Also, with MFTECmd output, I've found using the search bar on the top right is a better way to filter on a timeframe of interest so your search covers all the timestamp columns rather than just one. 

Check out the below links for more. Ping me with any questions.

https://www.kroll.com/en/insights/publications/cyber/anti-forensic-tactics/detecting-analyzing-timestomping-with-kape

https://youtu.be/-j7bQjWVixc
